### ISSUE TITLE
Feature Saturation

### ISSUE THREAD

**Issue by Kalissaac** [MomoMiles/ScrimBot#1]
Have we reached feature saturation? I'm not sure what else there is to add unless we want to branch out to other areas of functionality. If we do decide that it's complete, we should remove all the private info and make the repo public.

**Comment by MomoMiles** [comment]
The bot has not reached feature saturation. There are plenty more features to add. We have reached a point where the bot can be released to the public. Please check release v1.0.0 to see the first version of the bot, and report an issue here if you find one :)
